name: 'Retrieve archive from gist'
description: 'Retrieve archive from gist'
inputs:
  gist-url:
    description: 'URL of the targeted gist'
    required: true
  gist-filename:
    description: 'Filename in gist of encoded archive'
    required: true
  output-directory:
    description: 'Where to write retrieved folder'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - id: run-putter
      env:
        GIST_URL: ${{ inputs.gist-url }}
        GIST_FILENAME: ${{ inputs.gist-filename }}
        OUTPUT_DIRECTORY: ${{ inputs.output-directory }}
      name: Run getter.sh
      run: getter.sh $GIST_URL $GIST_FILENAME $OUTPUT_DIRECTORY
      shell: bash
