on:
  push:
    paths: '.github/workflows/test.yml'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GIST_PAT }}
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test actions
    steps:
      - uses: actions/checkout@v4
      
      - id: create-gist
        name: Create new gist
        run: |
          echo 'dummy file' > dummy_file.txt
          GIST_URL=$(gh gist create -d "testing gist" -f dummy_file.txt dummy_file.txt)
          echo $GIST_URL
          echo "gist-url=$GIST_URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create directory with unique content
        run: |
          mkdir input_directory
          UNIQUE_STRING="Unique content $(date +%s)"
          echo $UNIQUE_STRING > input_directory/testfile.txt
          echo 'unique-string=$UNIQUE_STRING' >> $GITHUB_OUTPUT

      - id: store-folder
        name: Store folder in gist
        uses: ./putter
        with:
          gist-url: ${{ steps.create-gist.outputs.gist-url }}
          input-directory: input_directory
      
      - name: Retrieve folder from gist
        uses: ./getter
        with:
          gist-url: ${{ steps.create-gist.outputs.gist-url }}
          gist-filename: ${{ steps.store-folder.outputs.gist-filename }}
          output-directory: output_directory
      
      - name: Echo contents of input and output files
        run: |
          echo "Input file content:"
          cat input_directory/testfile.txt
          echo "Output file content:"
          cat output_directory/testfile.txt

      - name: Confirm content
        run: diff input_directory/testfile.txt output_directory/testfile.txt

      - name: Clean up gist
        run: gh gist delete ${{ steps.create-gist.outputs.gist-url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
